//////////////////////////////////////////////////////////////////////////////
//
// Copyright 2025 Autodesk, Inc. All rights reserved.
//
// Use of this software is subject to the terms of the Autodesk license
// agreement provided at the time of installation or download, or which
// otherwise accompanies this software.
//
//////////////////////////////////////////////////////////////////////////////

#pragma once
#include "../Operations/OperationInput.h"
#include <string>

// THIS CLASS WILL BE VISIBLE TO AN API CLIENT.
// THIS HEADER FILE WILL BE GENERATED FROM NIDL.
#include "../../Core/OSMacros.h"

#ifdef CAMXINTERFACE_EXPORTS
# ifdef __COMPILING_ADSK_CAM_ADDITIVEFEAOPERATIONINPUT_CPP__
# define ADSK_CAM_ADDITIVEFEAOPERATIONINPUT_API XI_EXPORT
# else
# define ADSK_CAM_ADDITIVEFEAOPERATIONINPUT_API
# endif
#else
# define ADSK_CAM_ADDITIVEFEAOPERATIONINPUT_API XI_IMPORT
#endif

namespace adsk { namespace cam {
    class AdditiveFEADeckBuilder;
}}

namespace adsk { namespace cam {

/// !!!!! Warning !!!!!
/// ! This is hidden and not officially supported
/// !!!!! Warning !!!!!
/// 
class AdditiveFEAOperationInput : public OperationInput {
public:

    /// Applies the deck builder cards needed for the result
    /// calculation
    /// deck : A deck of solver cards
    void applyDeck(const core::Ptr<AdditiveFEADeckBuilder>& deck);

    /// Add a file with contents encoded as base64 to the solver's
    /// working directory.  This can be used to create PRM files or
    /// other resource files that the solver needs
    /// destFileName : The name of the resource file.  This name must match the card that refers to the resource, e.g. in PRMsCard
    /// fileContentsBase64 : The contents of the resource file, encoded as a base64 string.  With PRM files for example, you can get this string from the print settings using prmDataBase64()
    void addSolverFileContent(const std::string& destFileName, const std::string& fileContentsBase64);

    /// An AdditiveFEAOperation can generate two types of data:
    /// - the cell mesh, its generation also checks for errors
    /// - the actual simulation results
    /// By default, generating the AdditiveFEAOperation will only
    /// generate the former, setting the property to true will generate
    /// the result as well
    bool isGeneratingFEAResult() const;
    bool isGeneratingFEAResult(bool value);

    /// Name of the input file for additive FEA, including the
    /// base name and the file extension, but not the path
    std::string internalStudyName() const;

    /// Path to the work directory for additive FEA.  This
    /// directory contains the input file(s) initially.  After
    /// generation, it also contains mesh and/or result files and
    /// subdirectories
    std::string workDirectory() const;

    /// Text contents of the input deck file generated by applyDeck()
    std::string text() const;

    /// Contents of the PRM file from the print settings, encoded as a base64 string
    std::string prmDataBase64() const;

    ADSK_CAM_ADDITIVEFEAOPERATIONINPUT_API static const char* classType();
    ADSK_CAM_ADDITIVEFEAOPERATIONINPUT_API const char* objectType() const override;
    ADSK_CAM_ADDITIVEFEAOPERATIONINPUT_API void* queryInterface(const char* id) const override;
    ADSK_CAM_ADDITIVEFEAOPERATIONINPUT_API static const char* interfaceId() { return classType(); }

private:

    // Raw interface
    virtual void applyDeck_raw(AdditiveFEADeckBuilder* deck) = 0;
    virtual void addSolverFileContent_raw(const char* destFileName, const char* fileContentsBase64) = 0;
    virtual bool isGeneratingFEAResult_raw() const = 0;
    virtual bool isGeneratingFEAResult_raw(bool value) = 0;
    virtual char* internalStudyName_raw() const = 0;
    virtual char* workDirectory_raw() const = 0;
    virtual char* text_raw() const = 0;
    virtual char* prmDataBase64_raw() const = 0;
};

// Inline wrappers

inline void AdditiveFEAOperationInput::applyDeck(const core::Ptr<AdditiveFEADeckBuilder>& deck)
{
    applyDeck_raw(deck.get());
}

inline void AdditiveFEAOperationInput::addSolverFileContent(const std::string& destFileName, const std::string& fileContentsBase64)
{
    addSolverFileContent_raw(destFileName.c_str(), fileContentsBase64.c_str());
}

inline bool AdditiveFEAOperationInput::isGeneratingFEAResult() const
{
    bool res = isGeneratingFEAResult_raw();
    return res;
}

inline bool AdditiveFEAOperationInput::isGeneratingFEAResult(bool value)
{
    return isGeneratingFEAResult_raw(value);
}

inline std::string AdditiveFEAOperationInput::internalStudyName() const
{
    std::string res;

    char* p= internalStudyName_raw();
    if (p)
    {
        res = p;
        core::DeallocateArray(p);
    }
    return res;
}

inline std::string AdditiveFEAOperationInput::workDirectory() const
{
    std::string res;

    char* p= workDirectory_raw();
    if (p)
    {
        res = p;
        core::DeallocateArray(p);
    }
    return res;
}

inline std::string AdditiveFEAOperationInput::text() const
{
    std::string res;

    char* p= text_raw();
    if (p)
    {
        res = p;
        core::DeallocateArray(p);
    }
    return res;
}

inline std::string AdditiveFEAOperationInput::prmDataBase64() const
{
    std::string res;

    char* p= prmDataBase64_raw();
    if (p)
    {
        res = p;
        core::DeallocateArray(p);
    }
    return res;
}
}// namespace cam
}// namespace adsk

#undef ADSK_CAM_ADDITIVEFEAOPERATIONINPUT_API