#include <Cam/CamTypeDefs.h>
#include <Cam/AdditiveFEA/AdditiveFEAConvection.h>
#include <Cam/AdditiveFEA/AdditiveFEADeckBuilder.h>
#include <Cam/AdditiveFEA/AdditiveFEADeckBuilderCard.h>
#include <Cam/AdditiveFEA/AdditiveFEAOperation.h>
#include <Cam/AdditiveFEA/AdditiveFEAOperationInput.h>
#include <Cam/AdditiveFEA/AdditiveFEASTLMap.h>
#include <Cam/CAM/CAM.h>
#include <Cam/CAM/CAM3MFExportMetadataOptions.h>
#include <Cam/CAM/CAM3MFExportOptions.h>
#include <Cam/CAM/CAMAdditiveBuildExportFilter.h>
#include <Cam/CAM/CAMAdditiveBuildExportOptions.h>
#include <Cam/CAM/CAMAdditiveContainer.h>
#include <Cam/CAM/CAMAutodeskCLDExportOptions.h>
#include <Cam/CAM/CAMAutodeskCLDImportOptions.h>
#include <Cam/CAM/CAMExportFuture.h>
#include <Cam/CAM/CAMExportManager.h>
#include <Cam/CAM/CAMExportOptions.h>
#include <Cam/CAM/CAMFolder.h>
#include <Cam/CAM/CAMFolders.h>
#include <Cam/CAM/CAMFormlabsExportOptions.h>
#include <Cam/CAM/CAMHoleRecognition.h>
#include <Cam/CAM/CAMImportManager.h>
#include <Cam/CAM/CAMImportOptions.h>
#include <Cam/CAM/CAMInspectionResults.h>
#include <Cam/CAM/CAMMeasure.h>
#include <Cam/CAM/CAMPattern.h>
#include <Cam/CAM/CAMPatterns.h>
#include <Cam/CAM/ChildOperationList.h>
#include <Cam/CAM/CreateFromCAMTemplateInput.h>
#include <Cam/CAM/GenerateToolpathFuture.h>
#include <Cam/CAM/InspectionPathResult.h>
#include <Cam/CAM/InspectionPathResults.h>
#include <Cam/CAM/InspectionPointResult.h>
#include <Cam/CAM/InspectionPointResults.h>
#include <Cam/CAM/MachiningTime.h>
#include <Cam/CAM/PostProcessInput.h>
#include <Cam/CAM/Setup.h>
#include <Cam/CAM/SetupEvents.h>
#include <Cam/CAM/SetupGroup.h>
#include <Cam/CAM/SetupGroups.h>
#include <Cam/CAM/SetupInput.h>
#include <Cam/CAM/Setups.h>
#include <Cam/CAMEvents/CAMEventManager.h>
#include <Cam/CAMEvents/CAMEvents.h>
#include <Cam/CAMTemplate/CAMTemplate.h>
#include <Cam/CAMTemplate/CAMTemplateLibrary.h>
#include <Cam/CAMTemplate/CAMTemplateOperationInput.h>
#include <Cam/CAMTemplate/CAMTemplateOperations.h>
#include <Cam/CustomStrategy/CAMCustomStrategyManager.h>
#include <Cam/CustomStrategy/CustomOperationDefinitionInput.h>
#include <Cam/CustomStrategy/CustomOperationRegistrationResult.h>
#include <Cam/CustomStrategy/StrategyCommandDefinition.h>
#include <Cam/GeneratedData/GeneratedData.h>
#include <Cam/GeneratedData/GeneratedDataCollection.h>
#include <Cam/GeneratedData/OptimizedOrientationResult.h>
#include <Cam/GeneratedData/OptimizedOrientationResults.h>
#include <Cam/GeometrySelections/ArrangeSelection.h>
#include <Cam/GeometrySelections/ArrangeSelections.h>
#include <Cam/GeometrySelections/ChainSelection.h>
#include <Cam/GeometrySelections/CurveSelection.h>
#include <Cam/GeometrySelections/CurveSelections.h>
#include <Cam/GeometrySelections/FaceContourSelection.h>
#include <Cam/GeometrySelections/GeometrySelection.h>
#include <Cam/GeometrySelections/PocketRecognitionSelection.h>
#include <Cam/GeometrySelections/PocketSelection.h>
#include <Cam/GeometrySelections/SilhouetteSelection.h>
#include <Cam/GeometrySelections/SketchSelection.h>
#include <Cam/Global/CAMLibrary.h>
#include <Cam/Global/CAMLibraryManager.h>
#include <Cam/Global/CAMManager.h>
#include <Cam/Global/MachineDescription.h>
#include <Cam/Global/NetworkMachineEvents.h>
#include <Cam/Global/NetworkMachineIntegrationInput.h>
#include <Cam/Global/NetworkMachineIntegrationManager.h>
#include <Cam/HoleRecognition/RecognizedHole.h>
#include <Cam/HoleRecognition/RecognizedHoleGroup.h>
#include <Cam/HoleRecognition/RecognizedHoleGroups.h>
#include <Cam/HoleRecognition/RecognizedHoles.h>
#include <Cam/HoleRecognition/RecognizedHoleSegment.h>
#include <Cam/HoleRecognition/RecognizedHolesInput.h>
#include <Cam/Machine/AdditiveFFFLimitsMachineElement.h>
#include <Cam/Machine/AdditivePlatformMachineElement.h>
#include <Cam/Machine/ControllerConfigurationMachineElement.h>
#include <Cam/Machine/ExtruderMachineElement.h>
#include <Cam/Machine/ExtruderMachineElementInput.h>
#include <Cam/Machine/InteractionsMachineElement.h>
#include <Cam/Machine/KinematicsMachineElement.h>
#include <Cam/Machine/LaserMachineElement.h>
#include <Cam/Machine/LaserMachineElementInput.h>
#include <Cam/Machine/LinearMachineAxis.h>
#include <Cam/Machine/LinearMachineAxisConfiguration.h>
#include <Cam/Machine/LinearMachineAxisInput.h>
#include <Cam/Machine/Machine.h>
#include <Cam/Machine/MachineAxis.h>
#include <Cam/Machine/MachineAxisConfiguration.h>
#include <Cam/Machine/MachineAxisConfigurations.h>
#include <Cam/Machine/MachineAxisInput.h>
#include <Cam/Machine/MachineAxisRange.h>
#include <Cam/Machine/MachineCapabilities.h>
#include <Cam/Machine/MachineElement.h>
#include <Cam/Machine/MachineElementInput.h>
#include <Cam/Machine/MachineElements.h>
#include <Cam/Machine/MachineFromFileInput.h>
#include <Cam/Machine/MachineFromLibraryInput.h>
#include <Cam/Machine/MachineFromTemplateInput.h>
#include <Cam/Machine/MachineInput.h>
#include <Cam/Machine/MachineInteractionPair.h>
#include <Cam/Machine/MachineItem.h>
#include <Cam/Machine/MachineKinematics.h>
#include <Cam/Machine/MachineLibrary.h>
#include <Cam/Machine/MachinePart.h>
#include <Cam/Machine/MachinePartInput.h>
#include <Cam/Machine/MachineParts.h>
#include <Cam/Machine/MachineQuery.h>
#include <Cam/Machine/MachineSpindle.h>
#include <Cam/Machine/MachineSpindleInput.h>
#include <Cam/Machine/MachineToolStation.h>
#include <Cam/Machine/MachineToolStationInput.h>
#include <Cam/Machine/MultiAxisCombinationDPMFeedrateSettings.h>
#include <Cam/Machine/MultiAxisDPMFeedrateSettings.h>
#include <Cam/Machine/MultiAxisFeedrateSettings.h>
#include <Cam/Machine/MultiAxisFeedrateSettingsInput.h>
#include <Cam/Machine/MultiAxisInverseTimeFeedrateSettings.h>
#include <Cam/Machine/MultiAxisMachineElement.h>
#include <Cam/Machine/MultiAxisMachineElementInput.h>
#include <Cam/Machine/MultiAxisProgrammedFeedrateSettings.h>
#include <Cam/Machine/MultiAxisRetractAndReconfigureSettings.h>
#include <Cam/Machine/MultiAxisSingularityLinearizationSettings.h>
#include <Cam/Machine/MultiAxisSingularitySettings.h>
#include <Cam/Machine/PostProcessingMachineElement.h>
#include <Cam/Machine/RotaryMachineAxis.h>
#include <Cam/Machine/RotaryMachineAxisConfiguration.h>
#include <Cam/Machine/RotaryMachineAxisInput.h>
#include <Cam/Machine/ToolingCapabilitiesMachineElement.h>
#include <Cam/Machine/ToolingCapabilitiesMachineElementInput.h>
#include <Cam/MachineAvoidSelections/MachineAvoidDefaultSelection.h>
#include <Cam/MachineAvoidSelections/MachineAvoidDirectSelection.h>
#include <Cam/MachineAvoidSelections/MachineAvoidGroups.h>
#include <Cam/MachineAvoidSelections/MachineAvoidSelectionBase.h>
#include <Cam/ManufacturingModels/ManufacturingModel.h>
#include <Cam/ManufacturingModels/ManufacturingModelInput.h>
#include <Cam/ManufacturingModels/ManufacturingModels.h>
#include <Cam/ModifyUtility/AdditiveSetupUtility.h>
#include <Cam/ModifyUtility/ModifyUtility.h>
#include <Cam/NCProgram/NCProgram.h>
#include <Cam/NCProgram/NCProgramInput.h>
#include <Cam/NCProgram/NCProgramPostProcessOptions.h>
#include <Cam/NCProgram/NCPrograms.h>
#include <Cam/Operations/BooleanParameterValue.h>
#include <Cam/Operations/CadContours2dParameterValue.h>
#include <Cam/Operations/CadMachineAvoidGroupsParameterValue.h>
#include <Cam/Operations/CadMultiPointOnSurfaceParameterValue.h>
#include <Cam/Operations/CadObjectParameterValue.h>
#include <Cam/Operations/CAMArrangeParameterValue.h>
#include <Cam/Operations/CAMParameter.h>
#include <Cam/Operations/CAMParameters.h>
#include <Cam/Operations/ChoiceParameterValue.h>
#include <Cam/Operations/FloatParameterValue.h>
#include <Cam/Operations/IntegerParameterValue.h>
#include <Cam/Operations/Operation.h>
#include <Cam/Operations/OperationBase.h>
#include <Cam/Operations/OperationInput.h>
#include <Cam/Operations/Operations.h>
#include <Cam/Operations/OperationStrategy.h>
#include <Cam/Operations/ParameterValue.h>
#include <Cam/Operations/StringParameterValue.h>
#include <Cam/PocketRecognition/RecognizedPocket.h>
#include <Cam/PocketRecognition/RecognizedPockets.h>
#include <Cam/Post/PostConfiguration.h>
#include <Cam/Post/PostConfigurationQuery.h>
#include <Cam/Post/PostLibrary.h>
#include <Cam/PrintSetting/PrintSetting.h>
#include <Cam/PrintSetting/PrintSettingItem.h>
#include <Cam/PrintSetting/PrintSettingLibrary.h>
#include <Cam/PrintSetting/PrintSettingQuery.h>
#include <Cam/SandvikIntegration/SandvikIntegration.h>
#include <Cam/SandvikIntegration/SandvikIntegrationEvents.h>
#include <Cam/StockMaterials/DocumentStockMaterialLibrary.h>
#include <Cam/StockMaterials/StockMaterial.h>
#include <Cam/StockMaterials/StockMaterialLibrary.h>
#include <Cam/Tools/DocumentToolLibrary.h>
#include <Cam/Tools/Tool.h>
#include <Cam/Tools/ToolLibraries.h>
#include <Cam/Tools/ToolLibrary.h>
#include <Cam/Tools/ToolPreset.h>
#include <Cam/Tools/ToolPresets.h>
#include <Cam/Tools/ToolQuery.h>
#include <Cam/Tools/ToolQueryResult.h>
#include <Cam/Visibility/SetupVisibilityManager.h>
